// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package saml20.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import saml20.implementation.metadata.SPMetadataGenerator;
import saml20.implementation.security.CredentialRepository;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;

public class CreateSSOMetadataFile extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __spMetadata;
	private saml20.proxies.SPMetadata spMetadata;

	public CreateSSOMetadataFile(IContext context, IMendixObject spMetadata)
	{
		super(context);
		this.__spMetadata = spMetadata;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.spMetadata = __spMetadata == null ? null : saml20.proxies.SPMetadata.initialize(getContext(), __spMetadata);

		// BEGIN USER CODE
        CredentialRepository credRep = CredentialRepository.getInstance();
        credRep.updateConfiguration(getContext(), this.__spMetadata, null);

        this.spMetadata.setName("sp_metadata.xml");
        try (ByteArrayOutputStream out = SPMetadataGenerator.generate(getContext(), this.__spMetadata, credRep);
             ByteArrayInputStream inputStream = new ByteArrayInputStream(out.toByteArray())) {
            Core.storeFileDocumentContent(getContext(), this.__spMetadata, inputStream);
        }
        return true;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateSSOMetadataFile";
	}

	// BEGIN EXTRA CODE

	// END EXTRA CODE
}
